networks:
    default:
        name: service-sphere

services:
    db:
        build:
            context: ./dockerfiles/postgres
            dockerfile: postgres.dockerfile
        image: "service-sphere-postgres"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        restart: unless-stopped

    pgadmin:
        build:
            context: ./dockerfiles/pgadmin
            dockerfile: pgadmin.dockerfile
        image: "service-sphere-pgadmin"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@servicesphere.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - 8080:80
        restart: unless-stopped
